apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-aqvz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-aqvz
    app.kubernetes.io/part-of: ci1t-43256-0025-app
  name: devfile-sample-aqvz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-aqvz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-aqvz
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0025-tenant/ci1t-43256-0025-app/devfile-sample-aqvz@sha256:5e40ddac2fc3487a68d8e8a9b5ebbf30982395cc3642c88e30adc9abae681ddc
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
